/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeemanagementsystem;

/**
 *
 */
public class AddEmployeeForm extends javax.swing.JFrame {

    private String mCurrentEmploymentType = "FT";
    
    /**
     * Creates new form AddEmployeeForm
     */
    public AddEmployeeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAddEmpTitle = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelWorkLocation = new javax.swing.JLabel();
        fieldWorkLocation = new javax.swing.JTextField();
        labelSex = new javax.swing.JLabel();
        fieldSex = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        labelLastName = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        labelFirstName = new javax.swing.JLabel();
        labelEmpNum = new javax.swing.JLabel();
        fieldEmpNum = new javax.swing.JTextField();
        labelEmpSubtitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelType = new javax.swing.JLabel();
        buttonType = new javax.swing.JButton();
        labelDeductRate = new javax.swing.JLabel();
        fieldDeductRate = new javax.swing.JTextField();
        labelIncome = new javax.swing.JLabel();
        fieldIncome = new javax.swing.JTextField();
        fieldHoursPerWeek = new javax.swing.JTextField();
        labelHoursPerWeek = new javax.swing.JLabel();
        labelWeeksPerYear = new javax.swing.JLabel();
        fieldWeeksPerYear = new javax.swing.JTextField();
        labelPayrollSubtitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAddEmpTitle.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        labelAddEmpTitle.setText("Add Employee");
        labelAddEmpTitle.setToolTipText("");

        buttonCancel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(0, 204, 204));
        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonAdd.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        buttonAdd.setForeground(new java.awt.Color(0, 204, 204));
        buttonAdd.setText("Add Employee");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(26, 66, 175));

        labelWorkLocation.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelWorkLocation.setForeground(new java.awt.Color(255, 154, 24));
        labelWorkLocation.setText("Work Location");

        fieldWorkLocation.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        fieldWorkLocation.setForeground(new java.awt.Color(255, 154, 24));
        fieldWorkLocation.setToolTipText("");

        labelSex.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelSex.setForeground(new java.awt.Color(255, 154, 24));
        labelSex.setText("Sex");

        fieldSex.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        fieldSex.setForeground(new java.awt.Color(255, 154, 24));
        fieldSex.setToolTipText("");

        fieldLastName.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        fieldLastName.setForeground(new java.awt.Color(255, 154, 24));
        fieldLastName.setToolTipText("");

        labelLastName.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelLastName.setForeground(new java.awt.Color(255, 154, 24));
        labelLastName.setText("Last Name");

        fieldFirstName.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        fieldFirstName.setForeground(new java.awt.Color(255, 154, 24));
        fieldFirstName.setToolTipText("");

        labelFirstName.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelFirstName.setForeground(new java.awt.Color(255, 154, 24));
        labelFirstName.setText("First Name");

        labelEmpNum.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelEmpNum.setForeground(new java.awt.Color(255, 154, 24));
        labelEmpNum.setText("Employee Number");

        fieldEmpNum.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        fieldEmpNum.setForeground(new java.awt.Color(255, 154, 24));
        fieldEmpNum.setToolTipText("");

        labelEmpSubtitle.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        labelEmpSubtitle.setForeground(new java.awt.Color(255, 154, 24));
        labelEmpSubtitle.setText("Employee Information");
        labelEmpSubtitle.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelWorkLocation)
                                .addComponent(labelSex, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelLastName)
                                .addComponent(labelFirstName))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldSex, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldWorkLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelEmpNum)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fieldEmpNum, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelEmpSubtitle))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelEmpSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmpNum)
                    .addComponent(fieldEmpNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFirstName)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLastName)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSex)
                    .addComponent(fieldSex, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWorkLocation)
                    .addComponent(fieldWorkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jPanel2.setBackground(new java.awt.Color(26, 66, 175));

        labelType.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelType.setForeground(new java.awt.Color(0, 204, 204));
        labelType.setText("Employement Type");

        buttonType.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        buttonType.setForeground(new java.awt.Color(0, 204, 204));
        buttonType.setText("Full Time");
        buttonType.setToolTipText("Click on this button to change between full time and part time.");
        buttonType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTypeActionPerformed(evt);
            }
        });

        labelDeductRate.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelDeductRate.setForeground(new java.awt.Color(0, 204, 204));
        labelDeductRate.setText("Deduction Rate (%)");

        fieldDeductRate.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        fieldDeductRate.setForeground(new java.awt.Color(0, 204, 204));
        fieldDeductRate.setToolTipText("");

        labelIncome.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelIncome.setForeground(new java.awt.Color(0, 204, 204));
        labelIncome.setText("Annual Salary ($)");

        fieldIncome.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        fieldIncome.setForeground(new java.awt.Color(0, 204, 204));
        fieldIncome.setToolTipText("");
        fieldIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIncomeActionPerformed(evt);
            }
        });

        fieldHoursPerWeek.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        fieldHoursPerWeek.setForeground(new java.awt.Color(0, 204, 204));
        fieldHoursPerWeek.setToolTipText("");
        fieldHoursPerWeek.setEnabled(false);

        labelHoursPerWeek.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelHoursPerWeek.setForeground(new java.awt.Color(0, 204, 204));
        labelHoursPerWeek.setText("Hours/Week");
        labelHoursPerWeek.setEnabled(false);

        labelWeeksPerYear.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelWeeksPerYear.setForeground(new java.awt.Color(0, 204, 204));
        labelWeeksPerYear.setText("Weeks/Year");
        labelWeeksPerYear.setEnabled(false);

        fieldWeeksPerYear.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        fieldWeeksPerYear.setForeground(new java.awt.Color(0, 204, 204));
        fieldWeeksPerYear.setToolTipText("");
        fieldWeeksPerYear.setEnabled(false);
        fieldWeeksPerYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWeeksPerYearActionPerformed(evt);
            }
        });

        labelPayrollSubtitle.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        labelPayrollSubtitle.setForeground(new java.awt.Color(0, 204, 204));
        labelPayrollSubtitle.setText("Payroll Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDeductRate)
                            .addComponent(labelIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelWeeksPerYear)
                            .addComponent(labelType))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldDeductRate)
                            .addComponent(buttonType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldHoursPerWeek)
                            .addComponent(fieldIncome)
                            .addComponent(fieldWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelPayrollSubtitle))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelPayrollSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelType)
                    .addComponent(buttonType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDeductRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldDeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIncome)
                    .addComponent(fieldIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldHoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHoursPerWeek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWeeksPerYear))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(labelAddEmpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelAddEmpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTypeActionPerformed

        // Switch employment type
        mCurrentEmploymentType = "FT".equals(mCurrentEmploymentType) ? "PT" : "FT";

        // New employment type is Full Time
        if ("FT".equals(mCurrentEmploymentType)) {

            buttonType.setText("Full Time");
            labelIncome.setText("Annual Salary");
            labelHoursPerWeek.setEnabled(false);
            labelWeeksPerYear.setEnabled(false);
            fieldHoursPerWeek.setEnabled(false);
            fieldWeeksPerYear.setEnabled(false);

        }
        // New employment type if Part Time
        else {

            buttonType.setText("Part Time");
            labelIncome.setText("Hourly Wage");
            labelHoursPerWeek.setEnabled(true);
            labelWeeksPerYear.setEnabled(true);
            fieldHoursPerWeek.setEnabled(true);
            fieldWeeksPerYear.setEnabled(true);

        }

    }//GEN-LAST:event_buttonTypeActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        
        //UI.getInstance().cancelFormAddEmployee();
        
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        
        UI.getInstance().addFormAddEmployee();
        
    }//GEN-LAST:event_buttonAddActionPerformed

    private void fieldIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIncomeActionPerformed

    private void fieldWeeksPerYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWeeksPerYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWeeksPerYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployeeForm().setVisible(true);
            }
        });
    }
    
    // Field value getters
    public String getFieldEmpNum() {
        return fieldEmpNum.getText();
    }
    
    public String getFieldFirstName() {
        return fieldFirstName.getText();
    }
    
    public String getFieldLastName() {
        
        return fieldLastName.getText();
    }
    
    public String getFieldSex() {
        return fieldSex.getText();
    }
   
    public String getFieldWorkLocation() {
        return fieldWorkLocation.getText();
    }
    
    public String getFieldEmploymentType() {
        return mCurrentEmploymentType;
    }
    
    public String getFieldDeductRate() {
        return fieldDeductRate.getText();
    }
    
    public String getFieldIncome() {
        return fieldIncome.getText();
    }
    
    public String getFieldHoursPerWeek() {
        return fieldHoursPerWeek.getText();
    }
    
    public String getFieldWeeksPerYear() {
        return fieldWeeksPerYear.getText();
    }
    
    public void fillFieldsWithEmployee(int empNum, String firstName, String lastName, String sex, String workLoc, double deductRate, double yearlySalary) {
        
        fillGenericFields(empNum, firstName, lastName, sex, workLoc, deductRate, yearlySalary);
        
        mCurrentEmploymentType = "FT";
        buttonType.setText("Full Time");
        labelIncome.setText("Annual Salary");
        labelHoursPerWeek.setEnabled(false);
        labelWeeksPerYear.setEnabled(false);
        fieldHoursPerWeek.setEnabled(false);
        fieldWeeksPerYear.setEnabled(false);
        
    }
    
    public void fillFieldsWithEmployee(int empNum, String firstName, String lastName, String sex, String workLoc, double deductRate, double hourlyWage, double hoursPerWeek, double weeksPerYear) {
        
        fillGenericFields(empNum, firstName, lastName, sex, workLoc, deductRate, hourlyWage);
        
        mCurrentEmploymentType = "PT";
        buttonType.setText("Part Time");
        labelIncome.setText("Hourly Wage");
        labelHoursPerWeek.setEnabled(true);
        labelWeeksPerYear.setEnabled(true);
        fieldHoursPerWeek.setEnabled(true);
        fieldWeeksPerYear.setEnabled(true);
        
        fieldHoursPerWeek.setText(String.valueOf(hoursPerWeek));
        fieldWeeksPerYear.setText(String.valueOf(weeksPerYear));
        
    }
    
    private void fillGenericFields(int empNum, String firstName, String lastName, String sex, String workLoc, double deductRate, double income) {
        
        buttonAdd.setText("Finish");
        labelAddEmpTitle.setText("Edit Employee");
        
//        fieldEmpNum.setEnabled(false);
        
        fieldEmpNum.setText(String.valueOf(empNum));
        fieldFirstName.setText(firstName);
        fieldLastName.setText(lastName);
        fieldSex.setText(sex);
        fieldWorkLocation.setText(workLoc);
        
        fieldDeductRate.setText(String.valueOf(deductRate));
        fieldIncome.setText(String.valueOf(income));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonType;
    private javax.swing.JTextField fieldDeductRate;
    private javax.swing.JTextField fieldEmpNum;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldHoursPerWeek;
    private javax.swing.JTextField fieldIncome;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldSex;
    private javax.swing.JTextField fieldWeeksPerYear;
    private javax.swing.JTextField fieldWorkLocation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAddEmpTitle;
    private javax.swing.JLabel labelDeductRate;
    private javax.swing.JLabel labelEmpNum;
    private javax.swing.JLabel labelEmpSubtitle;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelHoursPerWeek;
    private javax.swing.JLabel labelIncome;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelPayrollSubtitle;
    private javax.swing.JLabel labelSex;
    private javax.swing.JLabel labelType;
    private javax.swing.JLabel labelWeeksPerYear;
    private javax.swing.JLabel labelWorkLocation;
    // End of variables declaration//GEN-END:variables
}
