/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeemanagementsystem;
import javax.swing.table.DefaultTableModel;

/**
 *
 */
public class Home extends javax.swing.JFrame {
    
    // METHODS
    
    /**
     * Creates new form MainInterface
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelViewEmp = new javax.swing.JPanel();
        labelViewTitle = new javax.swing.JLabel();
        panelEmp = new javax.swing.JPanel();
        labelEmpNum = new javax.swing.JLabel();
        labelVarEmpNum = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        labelVarFirstName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        labelVarLastName = new javax.swing.JLabel();
        labelSex = new javax.swing.JLabel();
        labelVarSex = new javax.swing.JLabel();
        labelWorkLocation = new javax.swing.JLabel();
        labelVarWorkLoc = new javax.swing.JLabel();
        labelPayrollSubtitle = new javax.swing.JLabel();
        labelType = new javax.swing.JLabel();
        labelVarType = new javax.swing.JLabel();
        labelDeductRate = new javax.swing.JLabel();
        labelVarDeductRate = new javax.swing.JLabel();
        labelIncome = new javax.swing.JLabel();
        labelVarIncome = new javax.swing.JLabel();
        labelHoursPerWeek = new javax.swing.JLabel();
        labelVarHoursPerWeek = new javax.swing.JLabel();
        labelWeeksPerYear = new javax.swing.JLabel();
        labelVarWeeksPerYear = new javax.swing.JLabel();
        labelGrossIncome = new javax.swing.JLabel();
        labelVarGrossIncome = new javax.swing.JLabel();
        labelDeduction = new javax.swing.JLabel();
        labelVarDeduction = new javax.swing.JLabel();
        labelNetIncome = new javax.swing.JLabel();
        labelVarNetIncome = new javax.swing.JLabel();
        panelDatabase = new javax.swing.JPanel();
        scrollPaneDatabase = new javax.swing.JScrollPane();
        tableDatabase = new javax.swing.JTable();
        buttonSearch = new javax.swing.JButton();
        fieldSearch = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        comboBoxSearchType = new javax.swing.JComboBox<>();
        labelTitle = new javax.swing.JLabel();
        labelTitle1 = new javax.swing.JLabel();
        buttonOpen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(26, 66, 175));

        panelViewEmp.setBackground(new java.awt.Color(26, 66, 175));
        panelViewEmp.setEnabled(false);

        labelViewTitle.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        labelViewTitle.setForeground(new java.awt.Color(255, 154, 24));
        labelViewTitle.setText("Employee Information Spreadsheet");
        labelViewTitle.setToolTipText("");

        panelEmp.setBackground(new java.awt.Color(26, 66, 175));

        labelEmpNum.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelEmpNum.setForeground(new java.awt.Color(255, 154, 24));
        labelEmpNum.setText("Employee Number");

        labelVarEmpNum.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarEmpNum.setForeground(new java.awt.Color(255, 154, 24));
        labelVarEmpNum.setText("_____________________________");

        labelFirstName.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelFirstName.setForeground(new java.awt.Color(255, 154, 24));
        labelFirstName.setText("First Name");

        labelVarFirstName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarFirstName.setForeground(new java.awt.Color(255, 154, 24));
        labelVarFirstName.setText("_____________________________");
        labelVarFirstName.setAutoscrolls(true);
        labelVarFirstName.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarFirstName.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarFirstName.setPreferredSize(new java.awt.Dimension(210, 16));

        labelLastName.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelLastName.setForeground(new java.awt.Color(255, 154, 24));
        labelLastName.setText("Last Name");

        labelVarLastName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarLastName.setForeground(new java.awt.Color(255, 154, 24));
        labelVarLastName.setText("_____________________________");
        labelVarLastName.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarLastName.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarLastName.setPreferredSize(new java.awt.Dimension(210, 16));

        labelSex.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelSex.setForeground(new java.awt.Color(255, 154, 24));
        labelSex.setText("Sex");

        labelVarSex.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarSex.setForeground(new java.awt.Color(255, 154, 24));
        labelVarSex.setText("_____________________________");
        labelVarSex.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarSex.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarSex.setPreferredSize(new java.awt.Dimension(210, 16));

        labelWorkLocation.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelWorkLocation.setForeground(new java.awt.Color(255, 154, 24));
        labelWorkLocation.setText("Work Location");
        labelWorkLocation.setToolTipText("");

        labelVarWorkLoc.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarWorkLoc.setForeground(new java.awt.Color(255, 154, 24));
        labelVarWorkLoc.setText("_____________________________");
        labelVarWorkLoc.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarWorkLoc.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarWorkLoc.setPreferredSize(new java.awt.Dimension(210, 16));

        labelPayrollSubtitle.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 30)); // NOI18N
        labelPayrollSubtitle.setForeground(new java.awt.Color(255, 154, 24));
        labelPayrollSubtitle.setText("Employee Payroll Information");

        labelType.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelType.setForeground(new java.awt.Color(255, 154, 24));
        labelType.setText("Employement Type");

        labelVarType.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarType.setForeground(new java.awt.Color(255, 154, 24));
        labelVarType.setText("_____________________________");
        labelVarType.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarType.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarType.setPreferredSize(new java.awt.Dimension(210, 16));

        labelDeductRate.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelDeductRate.setForeground(new java.awt.Color(255, 154, 24));
        labelDeductRate.setText("Deduction Rate (%)");

        labelVarDeductRate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarDeductRate.setForeground(new java.awt.Color(255, 154, 24));
        labelVarDeductRate.setText("_____________________________");
        labelVarDeductRate.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarDeductRate.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarDeductRate.setPreferredSize(new java.awt.Dimension(210, 16));

        labelIncome.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelIncome.setForeground(new java.awt.Color(255, 154, 24));
        labelIncome.setText("Annual Salary ($)");

        labelVarIncome.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarIncome.setForeground(new java.awt.Color(255, 154, 24));
        labelVarIncome.setText("_____________________________");
        labelVarIncome.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarIncome.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarIncome.setPreferredSize(new java.awt.Dimension(210, 16));

        labelHoursPerWeek.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelHoursPerWeek.setForeground(new java.awt.Color(255, 154, 24));
        labelHoursPerWeek.setText("Hours Per Week");
        labelHoursPerWeek.setEnabled(false);

        labelVarHoursPerWeek.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarHoursPerWeek.setForeground(new java.awt.Color(255, 154, 24));
        labelVarHoursPerWeek.setText("_____________________________");
        labelVarHoursPerWeek.setEnabled(false);
        labelVarHoursPerWeek.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarHoursPerWeek.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarHoursPerWeek.setPreferredSize(new java.awt.Dimension(210, 16));

        labelWeeksPerYear.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelWeeksPerYear.setForeground(new java.awt.Color(255, 154, 24));
        labelWeeksPerYear.setText("Weeks Per Year");
        labelWeeksPerYear.setEnabled(false);

        labelVarWeeksPerYear.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarWeeksPerYear.setForeground(new java.awt.Color(255, 154, 24));
        labelVarWeeksPerYear.setText("_____________________________");
        labelVarWeeksPerYear.setEnabled(false);
        labelVarWeeksPerYear.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarWeeksPerYear.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarWeeksPerYear.setPreferredSize(new java.awt.Dimension(210, 16));

        labelGrossIncome.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelGrossIncome.setForeground(new java.awt.Color(255, 154, 24));
        labelGrossIncome.setText("Gross Income ($)");

        labelVarGrossIncome.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarGrossIncome.setForeground(new java.awt.Color(255, 154, 24));
        labelVarGrossIncome.setText("_____________________________");
        labelVarGrossIncome.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarGrossIncome.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarGrossIncome.setPreferredSize(new java.awt.Dimension(210, 16));

        labelDeduction.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelDeduction.setForeground(new java.awt.Color(255, 154, 24));
        labelDeduction.setText("Deduction ($)");

        labelVarDeduction.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarDeduction.setForeground(new java.awt.Color(255, 154, 24));
        labelVarDeduction.setText("_____________________________");
        labelVarDeduction.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarDeduction.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarDeduction.setPreferredSize(new java.awt.Dimension(210, 16));

        labelNetIncome.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        labelNetIncome.setForeground(new java.awt.Color(255, 154, 24));
        labelNetIncome.setText("Net Income ($)");

        labelVarNetIncome.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelVarNetIncome.setForeground(new java.awt.Color(255, 154, 24));
        labelVarNetIncome.setText("_____________________________");
        labelVarNetIncome.setMaximumSize(new java.awt.Dimension(210, 16));
        labelVarNetIncome.setMinimumSize(new java.awt.Dimension(210, 16));
        labelVarNetIncome.setPreferredSize(new java.awt.Dimension(210, 16));

        javax.swing.GroupLayout panelEmpLayout = new javax.swing.GroupLayout(panelEmp);
        panelEmp.setLayout(panelEmpLayout);
        panelEmpLayout.setHorizontalGroup(
            panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpLayout.createSequentialGroup()
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpLayout.createSequentialGroup()
                        .addComponent(labelEmpNum)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelEmpLayout.createSequentialGroup()
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFirstName)
                            .addComponent(labelLastName)
                            .addComponent(labelSex))
                        .addGap(7, 334, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
            .addGroup(panelEmpLayout.createSequentialGroup()
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPayrollSubtitle)
                    .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelGrossIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDeductRate)
                            .addComponent(labelType)
                            .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelVarSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEmpLayout.createSequentialGroup()
                                        .addComponent(labelWorkLocation)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelVarWorkLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEmpLayout.createSequentialGroup()
                                        .addComponent(labelNetIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelVarNetIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEmpLayout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addComponent(labelVarGrossIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelEmpLayout.createSequentialGroup()
                                        .addComponent(labelDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelVarDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelEmpLayout.createSequentialGroup()
                                        .addComponent(labelHoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelVarHoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelVarWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelVarIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelVarDeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelVarType, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(labelVarLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelVarEmpNum)
                            .addComponent(labelVarFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelEmpLayout.setVerticalGroup(
            panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVarEmpNum)
                    .addComponent(labelEmpNum))
                .addGap(9, 9, 9)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFirstName)
                    .addComponent(labelVarFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpLayout.createSequentialGroup()
                        .addComponent(labelLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelSex)
                        .addGap(18, 18, 18)
                        .addComponent(labelWorkLocation))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpLayout.createSequentialGroup()
                        .addComponent(labelVarLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelVarSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelVarWorkLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(labelPayrollSubtitle)
                .addGap(18, 18, 18)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelType)
                    .addComponent(labelVarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDeductRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelVarDeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIncome)
                    .addComponent(labelVarIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHoursPerWeek)
                    .addComponent(labelVarHoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWeeksPerYear)
                    .addComponent(labelVarWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGrossIncome)
                    .addComponent(labelVarGrossIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDeduction)
                    .addComponent(labelVarDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNetIncome)
                    .addComponent(labelVarNetIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout panelViewEmpLayout = new javax.swing.GroupLayout(panelViewEmp);
        panelViewEmp.setLayout(panelViewEmpLayout);
        panelViewEmpLayout.setHorizontalGroup(
            panelViewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewEmpLayout.createSequentialGroup()
                .addGroup(panelViewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewEmpLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(panelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelViewEmpLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(labelViewTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelViewEmpLayout.setVerticalGroup(
            panelViewEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewEmpLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(labelViewTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatabase.setBackground(new java.awt.Color(26, 66, 175));

        tableDatabase.setBackground(new java.awt.Color(0, 204, 204));
        tableDatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp. Number", "Type", "First Name", "Last Name", "Work Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneDatabase.setViewportView(tableDatabase);
        if (tableDatabase.getColumnModel().getColumnCount() > 0) {
            tableDatabase.getColumnModel().getColumn(0).setPreferredWidth(90);
            tableDatabase.getColumnModel().getColumn(1).setPreferredWidth(80);
            tableDatabase.getColumnModel().getColumn(2).setPreferredWidth(80);
            tableDatabase.getColumnModel().getColumn(3).setPreferredWidth(80);
            tableDatabase.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        buttonSearch.setBackground(new java.awt.Color(0, 0, 0));
        buttonSearch.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        buttonSearch.setForeground(new java.awt.Color(0, 204, 204));
        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        fieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSearchActionPerformed(evt);
            }
        });

        buttonSave.setBackground(new java.awt.Color(0, 0, 0));
        buttonSave.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(0, 204, 204));
        buttonSave.setText("Click To Save Changes Made");
        buttonSave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonSave.setMaximumSize(new java.awt.Dimension(321, 35));
        buttonSave.setMinimumSize(new java.awt.Dimension(321, 35));
        buttonSave.setPreferredSize(new java.awt.Dimension(321, 35));
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonEdit.setBackground(new java.awt.Color(0, 0, 0));
        buttonEdit.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(0, 204, 204));
        buttonEdit.setText("Click To Edit An Employee's Info");
        buttonEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonRemove.setBackground(new java.awt.Color(0, 0, 0));
        buttonRemove.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        buttonRemove.setForeground(new java.awt.Color(0, 204, 204));
        buttonRemove.setText("Click To Remove Employee");
        buttonRemove.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonRemove.setMaximumSize(new java.awt.Dimension(321, 35));
        buttonRemove.setMinimumSize(new java.awt.Dimension(321, 35));
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        buttonAdd.setBackground(new java.awt.Color(0, 0, 0));
        buttonAdd.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        buttonAdd.setForeground(new java.awt.Color(0, 204, 204));
        buttonAdd.setText("Click To Add New Employee");
        buttonAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        comboBoxSearchType.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        comboBoxSearchType.setForeground(new java.awt.Color(0, 204, 204));
        comboBoxSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Name", "Last Name", "Work Location", "Full Time", "Part Time" }));

        javax.swing.GroupLayout panelDatabaseLayout = new javax.swing.GroupLayout(panelDatabase);
        panelDatabase.setLayout(panelDatabaseLayout);
        panelDatabaseLayout.setHorizontalGroup(
            panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatabaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDatabaseLayout.createSequentialGroup()
                        .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxSearchType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDatabaseLayout.createSequentialGroup()
                        .addComponent(scrollPaneDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDatabaseLayout.setVerticalGroup(
            panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatabaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBoxSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelTitle.setBackground(new java.awt.Color(26, 66, 175));
        labelTitle.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(0, 204, 204));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Employee Management System");
        labelTitle.setToolTipText("");

        labelTitle1.setBackground(new java.awt.Color(0, 0, 0));
        labelTitle1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        labelTitle1.setForeground(new java.awt.Color(255, 154, 24));
        labelTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle1.setText("Skyzone Mississauga");
        labelTitle1.setToolTipText("");

        buttonOpen.setBackground(new java.awt.Color(0, 0, 0));
        buttonOpen.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        buttonOpen.setForeground(new java.awt.Color(0, 204, 204));
        buttonOpen.setText("Open Files");
        buttonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonOpen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelViewEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelViewEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(buttonOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        
        UI.getInstance().beginFormAddEmployee();
        
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        // TODO add your handling code here:
        
        UI.getInstance().removeCurrentEmployee();
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
        
        UI.getInstance().editCurrentEmployee();
        
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
        
        searchDatabase();
        
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void fieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSearchActionPerformed
        // TODO add your handling code here:
        
        buttonSearchActionPerformed(evt);
        
    }//GEN-LAST:event_fieldSearchActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        
        UI.getInstance().saveDatabase();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenActionPerformed
        // TODO add your handling code here:
        
        UI.getInstance().openDatabase();
    }//GEN-LAST:event_buttonOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    public void searchDatabase() {
        String type = comboBoxSearchType.getSelectedItem().toString();
        
        UI.getInstance().searchEmployees(fieldSearch.getText(), type);
    }
   
    public void addRowToTable(Object[] row) {
        
        DefaultTableModel model = (DefaultTableModel) tableDatabase.getModel();
        model.addRow(row);
        tableDatabase.setModel(model);
        
    }
    
    public void clearTable() {
        
        DefaultTableModel model = (DefaultTableModel) tableDatabase.getModel();
        model.setRowCount(0);
        tableDatabase.setModel(model);
        
    }
    
    public void selectRow(int row) {
        
        tableDatabase.setRowSelectionInterval(row, row);
        
    }
    
    public javax.swing.JTable getTableDatabase() {
        return tableDatabase;
    }
    
    public void setVarEmpNum(int empNum, boolean isEmployee) {
        if (!isEmployee)
            labelVarEmpNum.setText("Select an employee...");
        else
            labelVarEmpNum.setText(String.valueOf(empNum));
    } 
    public void setVarFirstName(String firstName) {
        labelVarFirstName.setText(firstName);
    }
    public void setVarLastName(String lastName) {
        labelVarLastName.setText(lastName);
    }
    public void setVarSex(String sex) {
        labelVarSex.setText(sex);
    }
    public void setVarWorkLoc(String workLoc) {
        labelVarWorkLoc.setText(workLoc);
    }
    
    public void setVarEmploymentType(String type) {
        labelVarType.setText(type);
    }
    public void setVarDeductRate(double deductRate) {
        labelVarDeductRate.setText(String.format("%.2f", deductRate) + "%");
    }
    public void setVarIncome(double income) {
        labelVarIncome.setText("$" + String.format("%.2f", income));
    }
    public void setLabelIncome(String label) {
        labelIncome.setText(label);
    }
    public void setPartTimeLabels(boolean activate) {
        labelHoursPerWeek.setEnabled(activate);
        labelWeeksPerYear.setEnabled(activate);
        labelVarHoursPerWeek.setEnabled(activate);
        labelVarWeeksPerYear.setEnabled(activate);
    }
    public void setVarHoursPerWeek(double hoursPerWeek) {
        labelVarHoursPerWeek.setText(String.format("%.1f", hoursPerWeek));
    }
    public void setVarWeeksPerYear(double weeksPerYear) {
        labelVarWeeksPerYear.setText(String.format("%.1f", weeksPerYear));
    }
    public void setVarGrossIncome(double grossIncome) {
        labelVarGrossIncome.setText("$" + String.format("%.2f", grossIncome));
    }
    public void setVarDeduction(double deduction) {
        labelVarDeduction.setText("$" + String.format("%.2f", deduction));
    }
    public void setVarNetIncome(double netIncome) {
        labelVarNetIncome.setText("$" + String.format("%.2f", netIncome));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonOpen;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JComboBox<String> comboBoxSearchType;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JLabel labelDeductRate;
    private javax.swing.JLabel labelDeduction;
    private javax.swing.JLabel labelEmpNum;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelGrossIncome;
    private javax.swing.JLabel labelHoursPerWeek;
    private javax.swing.JLabel labelIncome;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelNetIncome;
    private javax.swing.JLabel labelPayrollSubtitle;
    private javax.swing.JLabel labelSex;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitle1;
    private javax.swing.JLabel labelType;
    private javax.swing.JLabel labelVarDeductRate;
    private javax.swing.JLabel labelVarDeduction;
    private javax.swing.JLabel labelVarEmpNum;
    private javax.swing.JLabel labelVarFirstName;
    private javax.swing.JLabel labelVarGrossIncome;
    private javax.swing.JLabel labelVarHoursPerWeek;
    private javax.swing.JLabel labelVarIncome;
    private javax.swing.JLabel labelVarLastName;
    private javax.swing.JLabel labelVarNetIncome;
    private javax.swing.JLabel labelVarSex;
    private javax.swing.JLabel labelVarType;
    private javax.swing.JLabel labelVarWeeksPerYear;
    private javax.swing.JLabel labelVarWorkLoc;
    private javax.swing.JLabel labelViewTitle;
    private javax.swing.JLabel labelWeeksPerYear;
    private javax.swing.JLabel labelWorkLocation;
    private javax.swing.JPanel panelDatabase;
    private javax.swing.JPanel panelEmp;
    private javax.swing.JPanel panelViewEmp;
    private javax.swing.JScrollPane scrollPaneDatabase;
    private javax.swing.JTable tableDatabase;
    // End of variables declaration//GEN-END:variables
}
